#!/usr/bin/env ruby

class Bakers_percentage
  def initialize
  end

  attr_reader :liquid

  def liquid=percent
    percent.between?(0,100) ? \
      @liquid = percent : \
      @liquid = nil
  end

end

class Recipe
  def initialize
  end

end


