#!/usr/bin/env ruby

class Bakers_percentage
  def initialize
  end

  attr_reader :liquids, :flours 

  #FIXME refactor these two, duh, along with all the impending
  # ingredients whose names we won't know
  # Actually, this is complete nonsense. Flours is always 100,
  # anything else can be any non-negative float. All flours
  # together are 100 by definition.
  def liquids=percent
    @liquids = percent.between?(0,100) ? percent : false
  end

  def flours=percent
    @flours = percent.between?(0,100) ? percent : false
  end

  def 

end

class Recipe
  def initialize
  end

end


